Algoritmo "5 da lista 3"

Var
   // Seção de Declarações das var
   nPar, nImpar, cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   cont<-1

   enquanto (cont < 1000) faca
      leia(cont)
      se cont % 2 = 0 entao

         npar<- cont
      escreval("O numero par é:",nPar )
      senao

         nimpar<- cont

   escreval("O numero impar é:",nImpar)
      fimse


   fimenquanto


Fimalgoritmo